spring:
  application:
    name: lms-gaming-platform
  
  # Secure Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lms_gaming_platform}
    username: ${DATABASE_USERNAME:lms_user}
    password: ${DATABASE_PASSWORD:${random.value}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA Security Configuration  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://your-auth-provider.com}
          
# Server Security
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict

# Management Security
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      
# JWT Security
jwt:
  secret: ${JWT_SECRET:}
  expiration: 3600000
  refresh-expiration: 86400000
  
# CORS Security
cors:
  allowed-origins: 
    - https://lms-mvp-jet.vercel.app
    - https://your-production-domain.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Logging Security
logging:
  level:
    com.learnhub: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/lms-gaming-platform.log